spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_forum?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: P@ssw0rd
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  output:
    ansi:
      enabled: ALWAYS

jwt:
  secret: P@ssw0rd
  expiration: 86400


